{% set name = "pyRserve" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b96b439bc63ed45315eae2bcf7be5301444fc21f7632743538d2c438d287b286

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - numpy
    - pip
    - python >=3.6
  run:
    - numpy
    - pytest
    - python >=3.6

test:
  imports:
    - pyRserve
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pypi.python.org/pypi/pyRserve/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python client to remotely access the R statistic package via network
  doc_url: https://pythonhosted.org/pyRserve/
  dev_url: https://github.com/ralhei/pyRserve

extra:
  recipe-maintainers:
    - anthchirp
    - trachtok
